init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master

# Build cache
cache:
- src\packages -> src\**\packages.config
- tools -> tools\packages.config